# Generated by Django 5.2 on 2025-06-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('portrait', models.ImageField(upload_to='persons')),
                ('birth_date', models.DateField(blank=True)),
                ('wiki_link', models.URLField(blank=True)),
            ],
        ),
    ]
