# Generated by Django 5.2 on 2025-07-10 14:16

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=embed_video.fields.EmbedVideoField(default='https://www.youtube.com/watch?v=SgmBsEoP1GI'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='person',
            name='portrait',
            field=models.ImageField(blank=True, upload_to='persons'),
        ),
    ]
