# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imdb", "0006_alter_movie_poster_alter_person_portrait_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(blank=True, upload_to="posters"),
        ),
        migrations.AlterField(
            model_name="person",
            name="portrait",
            field=models.ImageField(blank=True, upload_to="persons"),
        ),
    ]
