# Generated by Django 5.2 on 2025-06-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('poster', models.ImageField(upload_to='posters')),
                ('release_date', models.DateField(blank=True)),
                ('duration', models.IntegerField(blank=True)),
                ('age_rating', models.CharField(choices=[('G', 'General Audiences'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], max_length=5)),
                ('wiki_link', models.URLField(blank=True)),
            ],
        ),
    ]
