# Generated by Django 5.2 on 2025-06-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
